### ISSUE TITLE
JavaMailSender를 이용한 이메일 전송

### ISSUE THREAD

**Issue by nitronium102** [nitronium102/Spring-Practice#1]
## 1. 목적
Contact Us에 사용되는 이메일 전송 기능. 
사용자가 응답받을 자신의 이메일 주소와 문의 내용을 작성하면 내 이메일 주소로 문의가 오는 서비스.
(sender와 receiver 모두 내 이메일 주소. 본문에는 질문자의 이메일 주소와 문의 내용이 담김)
![image](https://user-images.githubusercontent.com/68282057/153715014-3bcc4a5b-2213-4444-b502-a3624b29b77d.png)

+ 텍스트 파일과 사진 첨부 기능도 포함함.
![image](https://user-images.githubusercontent.com/68282057/153715036-f9b409a2-6e21-4b2f-9704-21ad2fb43a98.png)

## 2. 구현
**1) `build.gradle`에 ` spring-boot-starter-mail` dependency 추가**
- JavaMailSender 사용 가능

**2) `application.yml`에 아래 코드 작성**
```
#mail connect
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: {MY_GMAIL_ADDRESS}
    password: {Gmail_APPICATION_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
```
